trigger: none
pr: none
schedules:
  - cron: "0 3 * * 2-6" # Run at 03:00 UTC Tuesday through Saturday (After the work day in Pacific, Mon-Fri)
    displayName: "Nightly Localization Build"
    branches:
      include:
        - main
    always: false # only run if there's code changes!

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: self
    type: git
    ref: master

steps:

- checkout: self
  clean: true
  submodules: false
  fetchDepth: 1 # Don't need a deep checkout for loc files!
  persistCredentials: true

- task: MicrosoftTDBuild.tdbuild-task.tdbuild-task.TouchdownBuildTask@1
  displayName: 'Touchdown Build - 37400, PRODEXT'
  inputs:
    teamId: 37400
    authId: '$(TouchdownApplicationID)'
    authKey: '$(TouchdownApplicationKey)'
    resourceFilePath: |
     **\Resources.resx
     **\Resource.resx
     **\Resources.resw
    outputDirectoryRoot: LocOutput
    appendRelativeDir: true
    pseudoSetting: Included

# Saving one of these makes it really easy to inspect the loc output...
- powershell: 'tar czf LocOutput.tar.gz LocOutput'
  displayName: 'PowerShell Script'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: LocOutput'
  inputs:
    PathtoPublish: LocOutput.tar.gz
    ArtifactName: LocOutput


